 <section class="footer index-section">
        <div class="box-container">
            <div class="box">
                <h3>Quick Links</h3> <br> 
                <br>
                <a href="index.html"><i class="fa-solid fa-house"></i>&nbsp;&nbsp;Home</a>
                <a href="about.html"><i class="fa-solid fa-user-tie"></i>&nbsp;&nbsp; About Us</a>
                <a href="jobs.html"><i class="fa-solid fa-briefcase"></i>&nbsp;&nbsp; Work With Us</a>
                <a href="apply.html"><i class="fa-solid fa-file"></i>&nbsp;&nbsp; Apply Now</a>
            </div>
    
            <div class="box">
                <h3>Our Socials</h3> <br>
                <br>
                <a href="#"><i class="fab fa-facebook"></i>&nbsp;&nbsp; Facebook</a>
                <a href="#"><i class="fab fa-twitter"></i>&nbsp;&nbsp; Twitter</a>
                <a href="#"><i class="fab fa-instagram"></i>&nbsp;&nbsp; Instgram</a>
                <a href="#"><i class="fab fa-linkedin"></i>&nbsp;&nbsp; LinkedIn</a>
            </div>
        </div>
        <div class="bottom">&copy; All rights reserved | <span>HealTech</span> | Created 2024</div>
</section>