<header>
            <div class="header-logo">
                <picture>
                    <source srcset="images/HEALTECH-WR.svg" media="(prefers-color-scheme: dark)">
                    <img src="images/HEALTECH.svg" alt="HEALTECH-logo">
                </picture>
            </div>
            <input type="checkbox" id="check">
            <label for="check" class="icons">
                <i class='bx bx-menu' id="menu-icon"></i>
                <i class='bx bx-x' id="close-icon" ></i>
            </label>
                <nav class="navbar">
                    <div class="ul">
                        <a href="index.php" style="--i:0;">Home</a>
                        <a href="about.php" style="--i:1;">About us</a>
                        <a href="jobs.php" style="--i:2;">Jobs</a>
                        <a href="apply.php" style="--i:3;">Apply</a>
                        <a href="login.php" style="--i:4"">Admin</a>
                        <a href="enhancements.php" style="--i:5;">Enhancements</a>
                    </div>                 
                </nav>
            <div class="semi circle"></div>
</header>